### ISSUE TITLE
CG is disabled

### ISSUE THREAD

**Issue by invkrh** [wangshusen/SparkGiant#1]
I notice that accelerated proximal SDCA is used, instead of the CG method
https://github.com/wangshusen/SparkGiant/blob/4c673c5f4a7a7bce85a74bd25754d608b30dde84/src/main/scala/logistic/Giant.scala#L191

This is different from the paper (page 5): https://arxiv.org/pdf/1709.03528v3.pdf

What is the idea behind this? Are they just equivalent? Or one is better than the other in terms of performance?

**Comment by wangshusen** [comment]
Dear Hao,

Thank you for reading my code and raising the question. I used this line of code to compare CG and SDCA. My conclusion is that CG is 1~2 times faster than SDCA. I recommend using CG.

Best,
Shusen

**Comment by invkrh** [comment]
Thank you for the reply. It's good to know that.

One followup question:
I find that there are several implementations of CG in the code.
https://github.com/wangshusen/SparkGiant/blob/master/src/main/scala/utils/CG.scala
https://github.com/wangshusen/SparkGiant/blob/master/src/main/scala/utils/CG2.scala

Which one should be used? Does Hessian reconstruction cause any performance downgrade?

**Comment by invkrh** [comment]
[`_****_`](

- url

)

**Comment by wangshusen** [comment]
I think either of the two implementations will work. I would recommend using "utils.CG.solver1", which does not form the Hessian. There is a little difference in the performance, but it is not significant at all.

The project is just a prototype for research purpose, and I haven't cleaned the code. I know the code is hard to read; I feel sorry. Feel free to ask me any question regarding the code and paper.

**Comment by invkrh** [comment]
Cool! Thank you. 
Actually, I find the code is clear enough to read and the comments and the paper helped a lot to understand the ideas.
Great work!
