### ISSUE TITLE
Label is not used

### ISSUE THREAD

**Issue by invkrh** [wangshusen/SparkGiant#3]
It seems that the logistic loss function doesn't use the label.
https://github.com/wangshusen/SparkGiant/blob/4c673c5f4a7a7bce85a74bd25754d608b30dde84/src/main/scala/logistic/Giant.scala#L15

The `y` is used nowhere but for `yMin` and `yMax`
https://github.com/wangshusen/SparkGiant/blob/4c673c5f4a7a7bce85a74bd25754d608b30dde84/src/main/scala/logistic/Common.scala#L113

What is the idea behind that?

**Comment by wangshusen** [comment]
Equation 10, Page 8 of my paper (version 3) https://arxiv.org/pdf/1709.03528.pdf

Logistic regression needn't know $x_j$ and $y_j$; instead, it needs their product $y_j * x_j$. Therefore, in the training, I map $(x_j, y_j)$ to $y_j*x_j$ in Line 112. In the rest of the code, $x$ is actually $x * y$. Does this make sense?

In the test, $x$ is $x$ (not $x * y$). The sign of $w * x$ is the predicted label.

**Comment by invkrh** [comment]
Thx
